all: cursed cursedwindows
cursed:
	gcc cursed.c -o cursed
cursedwindows:
	gcc cursedwindows.c -o cursedwindows
install:
	cp cursed ~/bin
	cp cursedwindows ~/bin
clean:
	 rm -f *.o   
	 rm -f cursed cursedwindows
	 rm -f *~

